# Generated by Django 4.2 on 2024-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_title', max_length=200)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('course', models.CharField(default='default_course', max_length=100)),
                ('lecturer_name', models.CharField(blank=True, default='Unknown Lecturer', max_length=100, null=True)),
                ('lecturer_id', models.CharField(blank=True, default='default_lecturer_id', max_length=20, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default='default_student_id', max_length=20, null=True)),
                ('course', models.CharField(default='default_course', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_group', max_length=100)),
                ('lecturer_name', models.CharField(blank=True, default='Unknown Lecturer', max_length=100, null=True)),
                ('lecturer_id', models.CharField(blank=True, default='default_lecturer_id', max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='default_group', max_length=100)),
                ('user_username', models.CharField(default='default_user', max_length=100)),
                ('user_id', models.CharField(blank=True, default='default_user_id', max_length=20, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(blank=True, default='default_lecturer_id', max_length=20, null=True)),
                ('department', models.CharField(default='default_department', max_length=100)),
                ('courses_taught', models.TextField(blank=True, default='[]', null=True)),
                ('username', models.CharField(default='lecturer_username', max_length=100)),
                ('name', models.CharField(blank=True, default='Lecturer Name', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default='default_student_id', max_length=20, null=True)),
                ('course', models.CharField(default='default_course', max_length=100)),
                ('assignment_id', models.CharField(blank=True, default='default_assignment_id', max_length=200, null=True)),
                ('marks', models.FloatField(default=0.0)),
                ('graded_by_name', models.CharField(blank=True, default='default_lecturer', max_length=100, null=True)),
                ('graded_by_id', models.CharField(blank=True, default='default_lecturer_id', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_username', models.CharField(default='default_user', max_length=100)),
                ('recipient_id', models.CharField(blank=True, default='default_user_id', max_length=20, null=True)),
                ('message', models.TextField(default='No message')),
                ('read_status', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(default='default_user', max_length=100)),
                ('user_id', models.CharField(blank=True, default='default_user_id', max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(default='default_transaction', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default='default_id', max_length=20, null=True)),
                ('course', models.CharField(default='default_course', max_length=100)),
                ('year_of_study', models.IntegerField(default=1)),
                ('username', models.CharField(default='student_username', max_length=100)),
                ('name', models.CharField(blank=True, default='Student Name', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(blank=True, default='default_assignment_id', max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, default='default_student_id', max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_username', max_length=100)),
                ('course', models.CharField(default='default_course', max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='default_location', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('username', models.CharField(default='user', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('user_type', models.CharField(blank=True, default='student', max_length=100, null=True)),
            ],
        ),
    ]
